[project]
name = "gtfs-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtfs-realtime-bindings>=1.0.0",
    "requests>=2.32.5",
]
